[build]
command = "npm run build"
publish = "public/"

#[[plugins]]
#package = "./netlify-plugin-debug-functions"

#[[plugins]]
#package = "netlify-plugin-debug-cache"

#[[plugins]]
#package = "@netlify/plugin-gatsby"

[[redirects]]
from = "/wat"
to = "/"
status = 200
